apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: flask-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://dummy:2630@cluster0.dyd41ym.mongodb.net/?appName=Cluster0"
        - name: DB_NAME
          value: "todoDB"
        - name: COLLECTION
          value: "todoItems"